Repository University-MakeUs-Challenge-ProductTeam/Official-Web-BE, pull requests merged in 2024-10, with the labels that each got.

#6 ✨ Feature: 활동 정보 관련 API
  src/main/java/umc/product/web/domain/activityInfo/controller/ActivityInfoController.java
  src/main/java/umc/product/web/domain/activityInfo/converter/ActivityInfoInfoConverter.java
  src/main/java/umc/product/web/domain/activityInfo/dto/ActivityInfoResponseDTO.java
  src/main/java/umc/product/web/domain/activityInfo/entity/ActivityInfo.java
  src/main/java/umc/product/web/domain/activityInfo/repository/ActivityInfoRepository.java
  src/main/java/umc/product/web/domain/activityInfo/service/ActivityInfoQueryService.java
  src/main/java/umc/product/web/domain/activityInfo/service/impl/ActivityInfoInfoQueryServiceImpl.java
  src/main/java/umc/product/web/global/error/code/handler/ActivityHandler.java
  src/main/java/umc/product/web/global/error/code/status/ErrorStatus.java
Labels: :sparkles: feature

#11 👷 Ci: test용 ci/cd 설정
  .github/workflows/test_deploy.yml
  Dockerfile
  build.gradle
Labels: :construction_worker: ci

#8 ✨ Feature: 모집일정 조회 api 추가
  src/main/java/umc/product/web/domain/requirement/controller/RequirementController.java
  src/main/java/umc/product/web/domain/requirement/converter/RequirementConverter.java
  src/main/java/umc/product/web/domain/requirement/dto/RequirementResponseDTO.java
  src/main/java/umc/product/web/domain/requirement/entity/RequirementSchool.java
  src/main/java/umc/product/web/domain/requirement/repository/RequirementPartRepository.java
  src/main/java/umc/product/web/domain/requirement/repository/RequirementSchoolRepository.java
  src/main/java/umc/product/web/domain/requirement/repository/StaffRepository.java
  src/main/java/umc/product/web/domain/requirement/service/RequirementQueryService.java
  src/main/java/umc/product/web/domain/requirement/service/impl/RequirementServiceImpl.java
  src/main/java/umc/product/web/domain/sponsor/controller/SponsorController.java
  src/main/java/umc/product/web/global/error/code/handler/RequirementHandler.java
  src/main/java/umc/product/web/global/error/code/status/ErrorStatus.java
Labels: :sparkles: feature

#12 ✨ Feature: 프로젝트 관련 엔티티 수정
  src/main/java/umc/product/web/domain/project/converter/ProjectConverter.java
  src/main/java/umc/product/web/domain/project/dto/ProjectResponseDTO.java
  src/main/java/umc/product/web/domain/project/entity/ParticipateSchool.java
  src/main/java/umc/product/web/domain/project/entity/Project.java
  src/main/java/umc/product/web/domain/project/entity/ProjectParticipateSchool.java
  src/main/java/umc/product/web/domain/project/repository/ParticipateSchoolRepository.java
  src/main/java/umc/product/web/domain/project/repository/ProjectParticipateSchoolRepository.java
  src/main/java/umc/product/web/domain/project/repository/ProjectSchoolRepository.java
  src/main/java/umc/product/web/domain/project/service/impl/ProjectQueryServiceImpl.java
Labels: :sparkles: feature

#16 🔧 Chore: 엔티티 수정
  .github/workflows/test_deploy.yml
  src/main/java/umc/product/web/domain/activityInfo/converter/ActivityInfoInfoConverter.java
  src/main/java/umc/product/web/domain/activityInfo/entity/ActivityInfo.java
  src/main/java/umc/product/web/domain/activityInfo/repository/ActivityInfoRepository.java
  src/main/java/umc/product/web/domain/activityInfo/service/impl/ActivityInfoInfoQueryServiceImpl.java
  src/main/java/umc/product/web/domain/centralEvent/domain/CentralEvent.java
  src/main/java/umc/product/web/domain/centralStaff/entity/CentralStaff.java
  src/main/java/umc/product/web/domain/project/entity/ParticipateSchool.java
  src/main/java/umc/product/web/domain/project/entity/Project.java
  src/main/java/umc/product/web/domain/project/repository/ParticipateSchoolRepository.java
  src/main/java/umc/product/web/domain/project/service/impl/ProjectQueryServiceImpl.java
  src/main/java/umc/product/web/domain/requirement/converter/RequirementConverter.java
  src/main/java/umc/product/web/domain/requirement/entity/RequirementSchool.java
  src/main/java/umc/product/web/domain/requirement/entity/SchoolStaff.java
  src/main/java/umc/product/web/domain/requirement/repository/SchoolStaffRepository.java
  src/main/java/umc/product/web/domain/requirement/repository/StaffRepository.java
  src/main/java/umc/product/web/domain/requirement/service/impl/RequirementServiceImpl.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
Labels: :wrench: chore

#19 🐛 Fix: 엔티티 생성 오류
  src/main/java/umc/product/web/domain/centralEvent/domain/CentralEvent.java
  src/main/java/umc/product/web/domain/centralEvent/domain/enums/EventType.java
Labels: :bug: bug

#21 ✨ Feature: 중앙운영진 조회 API 구현
  src/main/java/umc/product/web/domain/centralStaff/controller/CentralStaffController.java
  src/main/java/umc/product/web/domain/centralStaff/converter/CentralStaffConverter.java
  src/main/java/umc/product/web/domain/centralStaff/dto/CentralStaffResponseDTO.java
  src/main/java/umc/product/web/domain/centralStaff/entity/CentralStaff.java
  src/main/java/umc/product/web/domain/centralStaff/repository/CentralStaffRepository.java
  src/main/java/umc/product/web/domain/centralStaff/service/CentralStaffQueryService.java
  src/main/java/umc/product/web/domain/centralStaff/service/impl/CentralStaffQueryServiceImpl.java
  src/main/java/umc/product/web/global/error/code/status/ErrorStatus.java
  src/main/java/umc/product/web/global/validation/validator/CheckCursorValidator.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#29 🔧 Chore: 엔티티 속성 변환
  src/main/java/umc/product/web/domain/centralEvent/domain/CentralEvent.java
  src/main/java/umc/product/web/domain/centralEvent/domain/enums/EventType.java
Labels: :wrench: chore

#30 ✨ Feature: 참여 학교 조회 API 구현
  src/main/java/umc/product/web/domain/centralStaff/controller/CentralStaffController.java
  src/main/java/umc/product/web/domain/umc/controller/UMCController.java
  src/main/java/umc/product/web/domain/umc/converter/UMCConverter.java
  src/main/java/umc/product/web/domain/umc/dto/UMCResponseDTO.java
  src/main/java/umc/product/web/domain/umc/service/UMCQueryService.java
  src/main/java/umc/product/web/domain/umc/service/impl/UMCQueryServiceImpl.java
Labels: :sparkles: feature

#32 ✨ Feature: 프로젝트 기수, 플랫폼 조회 API 조회
  src/main/java/umc/product/web/domain/project/controller/ProjectController.java
  src/main/java/umc/product/web/domain/project/converter/ProjectConverter.java
  src/main/java/umc/product/web/domain/project/dto/ProjectResponseDTO.java
  src/main/java/umc/product/web/domain/project/repository/ProjectRepository.java
  src/main/java/umc/product/web/domain/project/service/ProjectQueryService.java
  src/main/java/umc/product/web/domain/project/service/impl/ProjectQueryServiceImpl.java
Labels: :sparkles: feature

#33 ✨ Feature: 프로젝트 플랫폼 조회 API 구현
  src/main/java/umc/product/web/domain/centralStaff/service/impl/CentralStaffQueryServiceImpl.java
  src/main/java/umc/product/web/domain/project/controller/ProjectController.java
  src/main/java/umc/product/web/domain/project/converter/ProjectConverter.java
  src/main/java/umc/product/web/domain/project/dto/ProjectResponseDTO.java
  src/main/java/umc/product/web/domain/project/repository/PlatformRepository.java
  src/main/java/umc/product/web/domain/project/repository/ProjectRepository.java
  src/main/java/umc/product/web/domain/project/service/ProjectQueryService.java
  src/main/java/umc/product/web/domain/project/service/impl/ProjectQueryServiceImpl.java
Labels: :sparkles: feature
