Repository University-MakeUs-Challenge-ProductTeam/Official-Web-BE, pull requests merged in 2024-11, with the labels that each got.

#37 ✨ Feature: 1차 조회 api 기능 개발
  src/main/java/umc/product/web/domain/centralEvent/controller/CentralEventController.java
  src/main/java/umc/product/web/domain/centralEvent/converter/CentralEventConverter.java
  src/main/java/umc/product/web/domain/centralEvent/repository/CentralEventRepository.java
  src/main/java/umc/product/web/domain/centralEvent/service/CentralEventService.java
  src/main/java/umc/product/web/domain/centralEvent/service/impl/CentralEventServiceImpl.java
  src/main/java/umc/product/web/domain/requirement/converter/RequirementConverter.java
  src/main/java/umc/product/web/domain/requirement/service/impl/RequirementServiceImpl.java
  src/main/java/umc/product/web/global/error/code/handler/CentralEventHandler.java
Labels: :sparkles: feature

#39 🐛 Fix: corConfig 수정
  src/main/java/umc/product/web/global/config/CorsConfig.java
Labels: :bug: bug

#41 ✨ Feature: UMC 전체 프로젝트 조회 API 구현
  src/main/java/umc/product/web/domain/project/controller/ProjectController.java
  src/main/java/umc/product/web/domain/project/converter/ProjectConverter.java
  src/main/java/umc/product/web/domain/project/dto/ProjectResponseDTO.java
  src/main/java/umc/product/web/domain/project/repository/ProjectRepository.java
  src/main/java/umc/product/web/domain/project/service/ProjectQueryService.java
  src/main/java/umc/product/web/domain/project/service/impl/ProjectQueryServiceImpl.java
  src/main/java/umc/product/web/global/error/ExceptionAdvice.java
Labels: :sparkles: feature

#43 ✨ Feature: 활동 조회 API generation 필드 제거 반영
  src/main/java/umc/product/web/domain/activityInfo/repository/ActivityInfoRepository.java
  src/main/java/umc/product/web/domain/activityInfo/service/impl/ActivityInfoInfoQueryServiceImpl.java
Labels: :sparkles: feature

#14 ✨ Feature: S3 세팅
  build.gradle
  src/main/java/umc/product/web/global/s3/config/S3Config.java
  src/main/java/umc/product/web/global/s3/controller/S3Controller.java
  src/main/java/umc/product/web/global/s3/converter/S3Converter.java
  src/main/java/umc/product/web/global/s3/dto/S3Request.java
  src/main/java/umc/product/web/global/s3/dto/S3Response.java
  src/main/java/umc/product/web/global/s3/service/S3Service.java
  src/main/java/umc/product/web/global/s3/service/impl/S3ServiceImpl.java
Labels: :sparkles: feature

#45 ✨ Feature: 중앙운영진 기수 조회 API 구현 및 URI 변경
  src/main/java/umc/product/web/domain/centralStaff/controller/CentralStaffController.java
  src/main/java/umc/product/web/domain/centralStaff/converter/CentralStaffConverter.java
  src/main/java/umc/product/web/domain/centralStaff/dto/CentralStaffResponseDTO.java
  src/main/java/umc/product/web/domain/centralStaff/repository/CentralStaffRepository.java
  src/main/java/umc/product/web/domain/centralStaff/service/CentralStaffQueryService.java
  src/main/java/umc/product/web/domain/centralStaff/service/impl/CentralStaffQueryServiceImpl.java
  src/main/java/umc/product/web/domain/project/controller/ProjectController.java
  src/main/java/umc/product/web/domain/umc/controller/UMCController.java
  src/main/java/umc/product/web/domain/umc/converter/UMCConverter.java
  src/main/java/umc/product/web/domain/umc/dto/UMCResponseDTO.java
  src/main/java/umc/product/web/domain/umc/service/UMCQueryService.java
  src/main/java/umc/product/web/domain/umc/service/impl/UMCQueryServiceImpl.java
Labels: :sparkles: feature

#35 ✨ Feature: 오프셋 기반으로 변경
  src/main/java/umc/product/web/domain/centralStaff/controller/CentralStaffController.java
  src/main/java/umc/product/web/domain/centralStaff/repository/CentralStaffRepository.java
  src/main/java/umc/product/web/domain/centralStaff/service/CentralStaffQueryService.java
  src/main/java/umc/product/web/domain/centralStaff/service/impl/CentralStaffQueryServiceImpl.java
  src/main/java/umc/product/web/domain/project/controller/ProjectController.java
  src/main/java/umc/product/web/domain/project/repository/ProjectRepository.java
  src/main/java/umc/product/web/domain/project/service/ProjectQueryService.java
  src/main/java/umc/product/web/domain/project/service/impl/ProjectQueryServiceImpl.java
  src/main/java/umc/product/web/global/error/code/status/ErrorStatus.java
  src/main/java/umc/product/web/global/validation/annotation/CheckPageValidation.java
  src/main/java/umc/product/web/global/validation/annotation/CheckSizeValidation.java
  src/main/java/umc/product/web/global/validation/validator/CheckPageValidator.java
  src/main/java/umc/product/web/global/validation/validator/CheckSizeValidator.java
Labels: :sparkles: feature

#47 🐛 Fix: 오프셋 기반 페이지네이션 수정
  src/main/java/umc/product/web/domain/centralStaff/converter/CentralStaffConverter.java
  src/main/java/umc/product/web/domain/centralStaff/dto/CentralStaffResponseDTO.java
  src/main/java/umc/product/web/domain/centralStaff/repository/CentralStaffRepository.java
  src/main/java/umc/product/web/domain/centralStaff/service/impl/CentralStaffQueryServiceImpl.java
  src/main/java/umc/product/web/domain/project/converter/ProjectConverter.java
  src/main/java/umc/product/web/domain/project/dto/ProjectResponseDTO.java
  src/main/java/umc/product/web/domain/project/repository/ProjectRepository.java
  src/main/java/umc/product/web/domain/project/service/impl/ProjectQueryServiceImpl.java
Labels: :bug: bug

#49 Refactor: 후원사 수정 & S3 삭제
  .github/workflows/test_deploy.yml
  src/main/java/umc/product/web/domain/sponsor/converter/SponsorConverter.java
  src/main/java/umc/product/web/domain/sponsor/dto/SponsorRequestDTO.java
  src/main/java/umc/product/web/global/s3/controller/S3Controller.java
Labels: :recycle: refactor

#53 ♻️ Refactor: eventType 변경
  src/main/java/umc/product/web/domain/centralEvent/domain/enums/EventType.java
Labels: :recycle: refactor
